### ISSUE TITLE
Missing start_editor.py in master branch

### ISSUE THREAD

**Issue by pankhurivanjani** [DynoRobotics/unity_ros2#12]
Hello! 
I am quite interested in this project and trying to run the turtlebot navigation example. With the master branch I am not able to find start_editor.py file in Assets and the documentation states running this file to setup and start unity environment. 
Am I missing out on something here?
Also, I tried running by switching the branch but i kept getting the error mentioned in [#10 ](https://github.com/DynoRobotics/UnityRos2/issues/10) during docker compose 

Which branch would developers advise for running it successfully?

Thanks,

**Comment by samiamlabs** [comment]
Hi @pankhurivanjani!

The setup.py script should no longer be needed for the master branch. Opening the project in Unity Hub should work fine (there will be some warnings in the console when opening the project though, but you can ignore them...).

The readthedocs dokumentation has not yet been updated to reflect this.

**Comment by samiamlabs** [comment]
Not sure exactly what error you are referring to, but using the precompiled docker image seems to work on my system. That can be started by running `docker-compose up` in `UnityRos2/Assets/ROS2/Examples/TurtlebotNavigation`.

**Comment by pankhurivanjani** [comment]
It is working now with docker image and the project opened well with unityhub. 
Thank you!

**Comment by hekje** [comment]
Hello!
This is a very interesting project and I tried to reproduce it on my system. I:
- installed Unity 2019.3.8f1 using the Unity hub
- cloned theUnityRos2 repo
- installed docker and docker-compose
- I used the "docker-compose up" command as described above to run the docker image.

But I am struggling with the "open the Unity Project using the Unity Hub" step: 
If I click ADD in the Unity Hub, I am not able to find the project to open it. (selecting the "UnityRos2" parent folder that holds Assets, docker, Packages and ProjectSettings does not work)
It seems that I am overlooking a rather trivial step, so I feel a bit silly to ask. But how can I open the Unity project?

Thanks!

**Comment by ErikOrjehag** [comment]
It seems to me that you are doing everything correct, its probably some silly problem.... I will try to reproduce if you have not already solved it by now?

**Comment by hekje** [comment]
Hi Erik,
Thanks for your comment!
It turned out a Unity Hub issue: after installing on a different computer and bypassing the Hub by opening the editor directly, I was able to open the project and run the demo.
But I do not like that this Hub just did not work without any error msg...

**Comment by ErikOrjehag** [comment]
Glad to hear it worked out for you. Please feel free to share your progress in 
https://forum.dynorobotics.se/t/use-cases-unityros2-projects-in-the-community/20
Its interesting to see what people are working on 😊
